name: Train LSTM Model

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Python
        run: |
          brew install python3

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install matplotlib

      - name: Train LSTM Model
        run: |
          python3 train.py

      - name: Upload Predictions Plot
        uses: actions/upload-artifact@v2
        with:
          name: predicciones
          path: predicciones.png
